var REPL = require('repl');
var mongoose = require ("mongoose");
var db = require('../../models/flag');
var repl = REPL.start("Flags >");

uristring = process.env.MONGOLAB_URI ||
            process.env.MONGOHQ_URL ||
            'mongodb://localhost:27017/flags';

mongoose.connect(uristring, function (err, res) {
  if (err) {
    console.log ('ERROR connecting to: ' + uristring + '. ' + err);
  } else {
    console.log ('Succeeded connected to: ' + uristring);
  }
});

repl.context.db = db;

db.Flag.collection.remove();

var flags =
[ { name: 'Andorra',
    isoCode: 'AD',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/ad.png' },
  { name: 'United Arab Emirates',
    isoCode: 'AE',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/ae.png' },
  { name: 'Afghanistan',
    isoCode: 'AF',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/af.png' },
  { name: 'Antigua and Barbuda',
    isoCode: 'AG',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/ag.png' },
  { name: 'Albania',
    isoCode: 'AL',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/al.png' },
  { name: 'Armenia',
    isoCode: 'AM',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/am.png' },
  { name: 'Angola',
    isoCode: 'AO',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/ao.png' },
  { name: 'Argentina',
    isoCode: 'AR',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/ar.png' },
  { name: 'Austria',
    isoCode: 'AT',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/at.png' },
  { name: 'Australia',
    isoCode: 'AU',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/au.png' },
  { name: 'Azerbaijan',
    isoCode: 'AZ',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/az.png' },
  { name: 'Bosnia and Herzegovina',
    isoCode: 'BA',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/ba.png' },
  { name: 'Barbados',
    isoCode: 'BB',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/bb.png' },
  { name: 'Bangladesh',
    isoCode: 'BD',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/bd.png' },
  { name: 'Belgium',
    isoCode: 'BE',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/be.png' },
  { name: 'Burkina Faso',
    isoCode: 'BF',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/bf.png' },
  { name: 'Bulgaria',
    isoCode: 'BG',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/bg.png' },
  { name: 'Bahrain',
    isoCode: 'BH',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/bh.png' },
  { name: 'Burundi',
    isoCode: 'BI',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/bi.png' },
  { name: 'Benin',
    isoCode: 'BJ',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/bj.png' },
  { name: 'Brunei Darussalam',
    isoCode: 'BN',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/bn.png' },
  { name: 'Bolivia',
    isoCode: 'BO',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/bo.png' },
  { name: 'Brazil',
    isoCode: 'BR',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/br.png' },
  { name: 'Bahamas',
    isoCode: 'BS',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/bs.png' },
  { name: 'Bhutan',
    isoCode: 'BT',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/bt.png' },
  { name: 'Botswana',
    isoCode: 'BW',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/bw.png' },
  { name: 'Belarus',
    isoCode: 'BY',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/by.png' },
  { name: 'Belize',
    isoCode: 'BZ',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/bz.png' },
  { name: 'Canada',
    isoCode: 'CA',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/ca.png' },
  { name: 'Congo',
    isoCode: 'CD',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/cd.png' },
  { name: 'Central African Republic',
    isoCode: 'CF',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/cf.png' },
  { name: 'Congo',
    isoCode: 'CG',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/cg.png' },
  { name: 'Switzerland',
    isoCode: 'CH',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/ch.png' },
  { name: 'Cote d’Ivoire',
    isoCode: 'CI',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/ci.png' },
  { name: 'Chile',
    isoCode: 'CL',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/cl.png' },
  { name: 'Cameroon',
    isoCode: 'CM',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/cm.png' },
  { name: 'China',
    isoCode: 'CN',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/cn.png' },
  { name: 'Colombia',
    isoCode: 'CO',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/co.png' },
  { name: 'Costa Rica',
    isoCode: 'CR',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/cr.png' },
  { name: 'Cuba',
    isoCode: 'CU',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/cu.png' },
  { name: 'Cape Verde',
    isoCode: 'CV',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/cv.png' },
  { name: 'Cyprus',
    isoCode: 'CY',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/cy.png' },
  { name: 'Czech Republic',
    isoCode: 'CZ',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/cz.png' },
  { name: 'Germany',
    isoCode: 'DE',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/de.png' },
  { name: 'Djibouti',
    isoCode: 'DJ',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/dj.png' },
  { name: 'Denmark',
    isoCode: 'DK',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/dk.png' },
  { name: 'Dominica',
    isoCode: 'DM',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/dm.png' },
  { name: 'Dominican Republic',
    isoCode: 'DO',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/do.png' },
  { name: 'Algeria',
    isoCode: 'DZ',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/dz.png' },
  { name: 'Ecuador',
    isoCode: 'EC',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/ec.png' },
  { name: 'Estonia',
    isoCode: 'EE',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/ee.png' },
  { name: 'Egypt',
    isoCode: 'EG',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/eg.png' },
  { name: 'Western Sahara',
    isoCode: 'EH',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/eh.png' },
  { name: 'Eritrea',
    isoCode: 'ER',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/er.png' },
  { name: 'Spain',
    isoCode: 'ES',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/es.png' },
  { name: 'Ethiopia',
    isoCode: 'ET',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/et.png' },
  { name: 'Finland',
    isoCode: 'FI',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/fi.png' },
  { name: 'Fiji',
    isoCode: 'FJ',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/fj.png' },
  { name: 'Micronesia',
    isoCode: 'FM',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/fm.png' },
  { name: 'France',
    isoCode: 'FR',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/fr.png' },
  { name: 'Gabon',
    isoCode: 'GA',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/ga.png' },
  { name: 'United Kingdom',
    isoCode: 'GB',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/gb.png' },
  { name: 'Grenada',
    isoCode: 'GD',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/gd.png' },
  { name: 'Georgia Republic',
    isoCode: 'GE',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/ge.png' },
  { name: 'Ghana',
    isoCode: 'GH',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/gh.png' },
  { name: 'Gambia',
    isoCode: 'GM',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/gm.png' },
  { name: 'Guinea',
    isoCode: 'GN',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/gn.png' },
  { name: 'Equatorial Guinea',
    isoCode: 'GQ',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/gq.png' },
  { name: 'Greece',
    isoCode: 'GR',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/gr.png' },
  { name: 'Guatemala',
    isoCode: 'GT',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/gt.png' },
  { name: 'Guinea-Bissau',
    isoCode: 'GW',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/gw.png' },
  { name: 'Guyana',
    isoCode: 'GY',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/gy.png' },
  { name: 'Honduras',
    isoCode: 'HN',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/hn.png' },
  { name: 'Croatia',
    isoCode: 'HR',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/hr.png' },
  { name: 'Haiti',
    isoCode: 'HT',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/ht.png' },
  { name: 'Hungary',
    isoCode: 'HU',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/hu.png' },
  { name: 'Indonesia',
    isoCode: 'ID',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/id.png' },
  { name: 'Ireland',
    isoCode: 'IE',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/ie.png' },
  { name: 'Israel',
    isoCode: 'IL',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/il.png' },
  { name: 'India',
    isoCode: 'IN',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/in.png' },
  { name: 'Iraq',
    isoCode: 'IQ',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/iq.png' },
  { name: 'Iran',
    isoCode: 'IR',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/ir.png' },
  { name: 'Iceland',
    isoCode: 'IS',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/is.png' },
  { name: 'Italy',
    isoCode: 'IT',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/it.png' },
  { name: 'Jamaica',
    isoCode: 'JM',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/jm.png' },
  { name: 'Jordan',
    isoCode: 'JO',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/jo.png' },
  { name: 'Japan',
    isoCode: 'JP',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/jp.png' },
  { name: 'Kenya',
    isoCode: 'KE',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/ke.png' },
  { name: 'Kyrgyzstan',
    isoCode: 'KG',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/kg.png' },
  { name: 'Cambodia',
    isoCode: 'KH',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/kh.png' },
  { name: 'Kiribati',
    isoCode: 'KI',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/ki.png' },
  { name: 'Comoros',
    isoCode: 'KM',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/km.png' },
  { name: 'Saint Kitts and Nevis',
    isoCode: 'KN',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/kn.png' },
  { name: 'North Korea',
    isoCode: 'KP',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/kp.png' },
  { name: 'South Korea',
    isoCode: 'KR',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/kr.png' },
  { name: 'Kosovo',
    isoCode: 'KS',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/ks.png' },
  { name: 'Kuwait',
    isoCode: 'KW',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/kw.png' },
  { name: 'Kazakhstan',
    isoCode: 'KZ',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/kz.png' },
  { name: 'Laos',
    isoCode: 'LA',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/la.png' },
  { name: 'Lebanon',
    isoCode: 'LB',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/lb.png' },
  { name: 'Saint Lucia',
    isoCode: 'LC',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/lc.png' },
  { name: 'Liechtenstein',
    isoCode: 'LI',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/li.png' },
  { name: 'Sri Lanka',
    isoCode: 'LK',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/lk.png' },
  { name: 'Liberia',
    isoCode: 'LR',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/lr.png' },
  { name: 'Lesotho',
    isoCode: 'LS',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/ls.png' },
  { name: 'Lithuania',
    isoCode: 'LT',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/lt.png' },
  { name: 'Luxembourg',
    isoCode: 'LU',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/lu.png' },
  { name: 'Latvia',
    isoCode: 'LV',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/lv.png' },
  { name: 'Libya',
    isoCode: 'LY',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/ly.png' },
  { name: 'Morocco',
    isoCode: 'MA',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/ma.png' },
  { name: 'Monaco',
    isoCode: 'MC',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/mc.png' },
  { name: 'Moldova',
    isoCode: 'MD',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/md.png' },
  { name: 'Montenegro',
    isoCode: 'ME',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/me.png' },
  { name: 'Madagascar',
    isoCode: 'MG',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/mg.png' },
  { name: 'Marshall Islands',
    isoCode: 'MH',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/mh.png' },
  { name: 'Macedonia',
    isoCode: 'MK',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/mk.png' },
  { name: 'Mali',
    isoCode: 'ML',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/ml.png' },
  { name: 'Myanmar',
    isoCode: 'MM',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/mm.png' },
  { name: 'Mongolia',
    isoCode: 'MN',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/mn.png' },
  { name: 'Mauritania',
    isoCode: 'MR',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/mr.png' },
  { name: 'Malta',
    isoCode: 'MT',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/mt.png' },
  { name: 'Mauritius',
    isoCode: 'MU',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/mu.png' },
  { name: 'Maldives',
    isoCode: 'MV',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/mv.png' },
  { name: 'Malawi',
    isoCode: 'MW',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/mw.png' },
  { name: 'Mexico',
    isoCode: 'MX',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/mx.png' },
  { name: 'Malaysia',
    isoCode: 'MY',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/my.png' },
  { name: 'Mozambique',
    isoCode: 'MZ',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/mz.png' },
  { name: 'Namibia',
    isoCode: 'NA',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/na.png' },
  { name: 'Niger',
    isoCode: 'NE',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/ne.png' },
  { name: 'Nigeria',
    isoCode: 'NG',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/ng.png' },
  { name: 'Nicaragua',
    isoCode: 'NI',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/ni.png' },
  { name: 'Netherlands',
    isoCode: 'NL',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/nl.png' },
  { name: 'Norway',
    isoCode: 'NO',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/no.png' },
  { name: 'Nepal',
    isoCode: 'NP',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/np.png' },
  { name: 'Nauru',
    isoCode: 'NR',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/nr.png' },
  { name: 'New Zealand',
    isoCode: 'NZ',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/nz.png' },
  { name: 'Oman',
    isoCode: 'OM',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/om.png' },
  { name: 'Panama',
    isoCode: 'PA',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/pa.png' },
  { name: 'Peru',
    isoCode: 'PE',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/pe.png' },
  { name: 'Papua New Guinea',
    isoCode: 'PG',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/pg.png' },
  { name: 'Philippines',
    isoCode: 'PH',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/ph.png' },
  { name: 'Pakistan',
    isoCode: 'PK',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/pk.png' },
  { name: 'Poland',
    isoCode: 'PL',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/pl.png' },
  { name: 'Portugal',
    isoCode: 'PT',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/pt.png' },
  { name: 'Palau',
    isoCode: 'PW',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/pw.png' },
  { name: 'Paraguay',
    isoCode: 'PY',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/py.png' },
  { name: 'Qatar',
    isoCode: 'QA',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/qa.png' },
  { name: 'Romania',
    isoCode: 'RO',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/ro.png' },
  { name: 'Serbia',
    isoCode: 'RS',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/rs.png' },
  { name: 'Russia',
    isoCode: 'RU',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/ru.png' },
  { name: 'Rwanda',
    isoCode: 'RW',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/rw.png' },
  { name: 'Saudi Arabia',
    isoCode: 'SA',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/sa.png' },
  { name: 'Solomon Islands',
    isoCode: 'SB',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/sb.png' },
  { name: 'Seychelles',
    isoCode: 'SC',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/sc.png' },
  { name: 'Sudan',
    isoCode: 'SD',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/sd.png' },
  { name: 'Sweden',
    isoCode: 'SE',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/se.png' },
  { name: 'Singapore',
    isoCode: 'SG',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/sg.png' },
  { name: 'Slovenia',
    isoCode: 'SI',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/si.png' },
  { name: 'Slovakia',
    isoCode: 'SK',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/sk.png' },
  { name: 'Sierra Leone',
    isoCode: 'SL',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/sl.png' },
  { name: 'San Marino',
    isoCode: 'SM',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/sm.png' },
  { name: 'Senegal',
    isoCode: 'SN',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/sn.png' },
  { name: 'Somalia',
    isoCode: 'SO',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/so.png' },
  { name: 'Suriname',
    isoCode: 'SR',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/sr.png' },
  { name: 'Sao Tome & Principe',
    isoCode: 'ST',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/st.png' },
  { name: 'El Salvador',
    isoCode: 'SV',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/sv.png' },
  { name: 'Syria',
    isoCode: 'SY',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/sy.png' },
  { name: 'Swaziland',
    isoCode: 'SZ',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/sz.png' },
  { name: 'Chad',
    isoCode: 'TD',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/td.png' },
  { name: 'Togo',
    isoCode: 'TG',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/tg.png' },
  { name: 'Thailand',
    isoCode: 'TH',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/th.png' },
  { name: 'Tajikistan',
    isoCode: 'TJ',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/tj.png' },
  { name: 'Timor-Leste',
    isoCode: 'TL',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/tl.png' },
  { name: 'Turkmenistan',
    isoCode: 'TM',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/tm.png' },
  { name: 'Tunisia',
    isoCode: 'TN',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/tn.png' },
  { name: 'Tonga',
    isoCode: 'TO',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/to.png' },
  { name: 'Turkey',
    isoCode: 'TR',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/tr.png' },
  { name: 'Trinidad and Tobago',
    isoCode: 'TT',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/tt.png' },
  { name: 'Tuvalu',
    isoCode: 'TV',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/tv.png' },
  { name: 'Taiwan',
    isoCode: 'TW',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/tw.png' },
  { name: 'Tanzania',
    isoCode: 'TZ',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/tz.png' },
  { name: 'Ukraine',
    isoCode: 'UA',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/ua.png' },
  { name: 'Uganda',
    isoCode: 'UG',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/ug.png' },
  { name: 'United States',
    isoCode: 'US',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/us.png' },
  { name: 'Uruguay',
    isoCode: 'UY',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/uy.png' },
  { name: 'Uzbekistan',
    isoCode: 'UZ',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/uz.png' },
  { name: 'Holy See (Vatican City State)',
    isoCode: 'VA',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/va.png' },
  { name: 'Saint Vincent and the Grenadines',
    isoCode: 'VC',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/vc.png' },
  { name: 'Venezuela',
    isoCode: 'VE',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/ve.png' },
  { name: 'Viet Nam',
    isoCode: 'VN',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/vn.png' },
  { name: 'Vanuatu',
    isoCode: 'VU',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/vu.png' },
  { name: 'Samoa',
    isoCode: 'WS',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/ws.png' },
  { name: 'Yemen',
    isoCode: 'YE',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/ye.png' },
  { name: 'South Africa',
    isoCode: 'ZA',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/za.png' },
  { name: 'Zambia',
    isoCode: 'ZM',
    GoodFlag: true,
    url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/zm.png' }
 ];

flags.forEach(function(flag){
  db.Flag.create({
    name: flag.name,
    isoCode: flag.isoCode,
    GoodFlag: flag.GoodFlag,
    url: flag.url
  },

  function(err, flag){
    console.log('*******FLAG CREATED******');
    console.log(flag.name);
    console.log(flag);
    flag.save();
  })
});

db.Flag.create({
  name: 'Zimbabwe',
  isoCode: 'ZW',
  GoodFlag: true,
  url: 'http://pataruco.s3.amazonaws.com/good-flag/flags/zw.png'
  },
  function(err, flag){
    console.log('*******FLAG CREATED******');
    console.log(flag.name);
    console.log(flag);
    console.log('*******DATABASE SEEDED******');

    flag.save();
    process.exit();
});
